/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package application;

import java.awt.GridLayout;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import tabuleiro.Jogo;
import tabuleiro.Tabuleiro;

/**
 *
 * @author bruno
 */
public class IUPrincipal extends javax.swing.JFrame {

    public Jogo jogo;
    public Tabuleiro tabuleiro;
    public int[][] matriz;
    public int posVazia;
    public int operacao;
    
    /**
     * Creates new form Principal
     */
    public IUPrincipal() {
        initComponents();
        
        //Interface padrão ao sistema.
        try {    
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
            SwingUtilities.updateComponentTreeUI(this);
            
        } catch(Exception e){
            e.printStackTrace();
        }
        
        //Centralizando a aplicação
        this.setLocationRelativeTo(null);
        
        //Titulo da aplicação
        this.setTitle("Jogo dos quadrados");
        
        //Inicializando variaveis
        tabuleiro = new Tabuleiro();
        jogo = new Jogo();
        this.operacao = -1;
        
        this.radioAnicacaoON.setSelected(true);
        this.radioAnimacaoOFF.setSelected(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblMetodo = new javax.swing.JLabel();
        radioAnicacaoON = new javax.swing.JRadioButton();
        radioAnimacaoOFF = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        tfNumPassos = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        btn1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btn1.setText("1");

        btn2.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btn2.setText("2");

        btn3.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btn3.setText("3");

        btn4.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btn4.setText("4");

        btn5.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btn5.setText("5");

        btn6.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btn6.setText("6");

        btn7.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btn7.setText("7");

        btn8.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btn8.setText("8");

        btn9.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N

        jLabel1.setText("Tabuleiro");

        jLabel2.setText("Metódo de resolução:");

        lblMetodo.setText("Escolha um método");

        radioAnicacaoON.setText("Ligar animação");
        radioAnicacaoON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioAnicacaoONActionPerformed(evt);
            }
        });

        radioAnimacaoOFF.setText("Desligar animação");
        radioAnimacaoOFF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioAnimacaoOFFActionPerformed(evt);
            }
        });

        jButton1.setText("Resolver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tfNumPassos.setEditable(false);

        jLabel3.setText("Movimentos realizados:");

        jMenu1.setText("Novo");

        jMenu4.setText("Inicializar tabuleiro");

        jMenuItem8.setText("Automaticamente");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem8);

        jMenuItem9.setText("Manualmente");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem9);

        jMenu1.add(jMenu4);

        jMenuItem7.setText("Sair");
        jMenu1.add(jMenuItem7);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Metódos de resolução");

        jMenuItem1.setText("Heurística aletória");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem2.setText("Heurística análise em um nível");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem3.setText("Heurística análise em dois nível");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuItem4.setText("Heurística pessoal");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Ajuda");

        jMenuItem5.setText("Sobre");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(radioAnicacaoON)
                            .addComponent(lblMetodo)
                            .addComponent(radioAnimacaoOFF))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton1)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfNumPassos))))
                .addGap(48, 48, 48))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblMetodo)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(radioAnicacaoON)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(radioAnimacaoOFF)))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(4, 4, 4)
                .addComponent(tfNumPassos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
        
        IUEntradaDados cad = new IUEntradaDados(this, true);
        cad.setLocationRelativeTo(this);
        cad.setVisible(true);
        this.matriz = cad.matriz;
        this.posVazia = cad.posVazia;
        
        Tabuleiro tabuleiroAux = new Tabuleiro();
        tabuleiro.setMatriz(matriz);
        tabuleiro.setPosVazia(posVazia);
        
        this.tabuleiro = tabuleiroAux;
        System.out.println(tabuleiro);
        btn1.setText(String.valueOf(tabuleiro.matriz[0][0]));
        btn2.setText(String.valueOf(tabuleiro.matriz[0][1]));
        btn3.setText(String.valueOf(tabuleiro.matriz[0][2]));
        btn4.setText(String.valueOf(tabuleiro.matriz[1][0]));
        btn5.setText(String.valueOf(tabuleiro.matriz[1][1]));
        btn6.setText(String.valueOf(tabuleiro.matriz[1][2]));
        btn7.setText(String.valueOf(tabuleiro.matriz[2][0]));
        btn8.setText(String.valueOf(tabuleiro.matriz[2][1]));
        btn9.setText(String.valueOf(tabuleiro.matriz[2][2]));
        
        if(btn1.getText().equals("-1")) btn1.setText("");
        else if(btn2.getText().equals("-1")) btn2.setText("");
        else if(btn3.getText().equals("-1")) btn3.setText("");
        else if(btn4.getText().equals("-1")) btn4.setText("");
        else if(btn5.getText().equals("-1")) btn5.setText("");
        else if(btn6.getText().equals("-1")) btn6.setText("");
        else if(btn7.getText().equals("-1")) btn7.setText("");
        else if(btn8.getText().equals("-1")) btn8.setText("");
        else if(btn9.getText().equals("-1")) btn9.setText("");

        cad.dispose();
        
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        
        Jogo jogo = new Jogo();
        jogo.embaralhar();
        this.tabuleiro = jogo.tabuleiroInicial;
        System.out.println(tabuleiro);
        btn1.setText(String.valueOf(tabuleiro.matriz[0][0]));
        btn2.setText(String.valueOf(tabuleiro.matriz[0][1]));
        btn3.setText(String.valueOf(tabuleiro.matriz[0][2]));
        btn4.setText(String.valueOf(tabuleiro.matriz[1][0]));
        btn5.setText(String.valueOf(tabuleiro.matriz[1][1]));
        btn6.setText(String.valueOf(tabuleiro.matriz[1][2]));
        btn7.setText(String.valueOf(tabuleiro.matriz[2][0]));
        btn8.setText(String.valueOf(tabuleiro.matriz[2][1]));
        btn9.setText(String.valueOf(tabuleiro.matriz[2][2]));

        if(btn1.getText().equals("-1")) btn1.setText("");
        else if(btn2.getText().equals("-1")) btn2.setText("");
        else if(btn3.getText().equals("-1")) btn3.setText("");
        else if(btn4.getText().equals("-1")) btn4.setText("");
        else if(btn5.getText().equals("-1")) btn5.setText("");
        else if(btn6.getText().equals("-1")) btn6.setText("");
        else if(btn7.getText().equals("-1")) btn7.setText("");
        else if(btn8.getText().equals("-1")) btn8.setText("");
        else if(btn9.getText().equals("-1")) btn9.setText("");
        
        this.tfNumPassos.setText("");
        
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        
        this.lblMetodo.setText("Método Aleatório");
        this.operacao = 0;
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        if(this.operacao == 0){ //Aleatória
            
            Jogo jogo = new Jogo();
            jogo.tabuleiroInicial = this.tabuleiro;
            jogo.aleatorio();
            System.out.println(jogo.contadorSolucao);
            if(this.radioAnicacaoON.isSelected() && !this.radioAnimacaoOFF.isSelected()){
                
                Pintar pincel = new Pintar(jogo);
                new Thread(pincel).start();
            }
            else if(!this.radioAnicacaoON.isSelected() && this.radioAnimacaoOFF.isSelected()){
                
                pintarSomenteResultadoFinal(jogo);
            }

        }
        else if(this.operacao == 1){ //Um nivel
            
            Jogo jogo = new Jogo();
            jogo.tabuleiroInicial = this.tabuleiro;
            jogo.heuristicaEmUmNivel();
            System.out.println(jogo.contadorSolucao);
            if(this.radioAnicacaoON.isSelected() && !this.radioAnimacaoOFF.isSelected()){
                
                Pintar pincel = new Pintar(jogo);
                new Thread(pincel).start();
            }
            else if(!this.radioAnicacaoON.isSelected() && this.radioAnimacaoOFF.isSelected()){
                
                pintarSomenteResultadoFinal(jogo);
            }
            
        }
        else if(this.operacao == 2){ //Dois niveis
            
            Jogo jogo = new Jogo();
            jogo.tabuleiroInicial = this.tabuleiro;
            jogo.heuristicaEmDoisNiveis();
            System.out.println(jogo.contadorSolucao);
            if(this.radioAnicacaoON.isSelected() && !this.radioAnimacaoOFF.isSelected()){
                
                Pintar pincel = new Pintar(jogo);
                new Thread(pincel).start();
            }
            else if(!this.radioAnicacaoON.isSelected() && this.radioAnimacaoOFF.isSelected()){
                
                pintarSomenteResultadoFinal(jogo);
            }
            
        }
        else if(this.operacao == 3){ //Pessoal
            
            Jogo jogo = new Jogo();
            jogo.tabuleiroInicial = this.tabuleiro;
            jogo.heuristicaPessoal();
            System.out.println(jogo.contadorSolucao);
            if(this.radioAnicacaoON.isSelected() && !this.radioAnimacaoOFF.isSelected()){
                
                Pintar pincel = new Pintar(jogo);
                new Thread(pincel).start();
            }
            else if(!this.radioAnicacaoON.isSelected() && this.radioAnimacaoOFF.isSelected()){
                
                pintarSomenteResultadoFinal(jogo);
                
            }
            
        }
        else if(this.operacao == -1) { //Nenhuma operação selecionada
            
            JOptionPane.showMessageDialog(null, "Nenhum método de resolução escolhido!");
        }
                
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        
        this.lblMetodo.setText("Método Heurística em um nível");
        this.operacao = 1;
        
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        
        this.lblMetodo.setText("Método Heurística em dois níveis");
        this.operacao = 2;
        
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        
        this.lblMetodo.setText("Método Heurística pessoal");
        this.operacao = 3;
        
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        
        IUSobre cad = new IUSobre(this, true);
        cad.setLocationRelativeTo(this);
        cad.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void radioAnimacaoOFFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioAnimacaoOFFActionPerformed
        // TODO add your handling code here:
        
        this.radioAnicacaoON.setSelected(false);
        
    }//GEN-LAST:event_radioAnimacaoOFFActionPerformed

    private void radioAnicacaoONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioAnicacaoONActionPerformed
        // TODO add your handling code here:
        
        this.radioAnimacaoOFF.setSelected(false);
        
    }//GEN-LAST:event_radioAnicacaoONActionPerformed

    public void pintarSomenteResultadoFinal(Jogo jogo){
        
        this.tabuleiro = jogo.tabuleiroInicial;
        
        btn1.setText(String.valueOf(tabuleiro.matriz[0][0]));
        btn2.setText(String.valueOf(tabuleiro.matriz[0][1]));
        btn3.setText(String.valueOf(tabuleiro.matriz[0][2]));
        btn4.setText(String.valueOf(tabuleiro.matriz[1][0]));
        btn5.setText(String.valueOf(tabuleiro.matriz[1][1]));
        btn6.setText(String.valueOf(tabuleiro.matriz[1][2]));
        btn7.setText(String.valueOf(tabuleiro.matriz[2][0]));
        btn8.setText(String.valueOf(tabuleiro.matriz[2][1]));
        btn9.setText(String.valueOf(tabuleiro.matriz[2][2]));

        if(btn1.getText().equals("-1")) btn1.setText("");
        else if(btn2.getText().equals("-1")) btn2.setText("");
        else if(btn3.getText().equals("-1")) btn3.setText("");
        else if(btn4.getText().equals("-1")) btn4.setText("");
        else if(btn5.getText().equals("-1")) btn5.setText("");
        else if(btn6.getText().equals("-1")) btn6.setText("");
        else if(btn7.getText().equals("-1")) btn7.setText("");
        else if(btn8.getText().equals("-1")) btn8.setText("");
        else if(btn9.getText().equals("-1")) btn9.setText("");
        
        this.tfNumPassos.setText(jogo.contadorSolucao + "");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IUPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IUPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IUPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IUPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IUPrincipal().setVisible(true);
            }
        });
        
        
    }

    public class Pintar extends Thread{
        
        public Jogo jogo;
        
        public Pintar(Jogo jogo){
            this.jogo = jogo;
        }
        
        public void run() {
            
            int cont = 1;
            for(Tabuleiro t : jogo.getListaResultado()){

                btn1.setText(String.valueOf(t.matriz[0][0]));
                btn2.setText(String.valueOf(t.matriz[0][1]));
                btn3.setText(String.valueOf(t.matriz[0][2]));
                btn4.setText(String.valueOf(t.matriz[1][0]));
                btn5.setText(String.valueOf(t.matriz[1][1]));
                btn6.setText(String.valueOf(t.matriz[1][2]));
                btn7.setText(String.valueOf(t.matriz[2][0]));
                btn8.setText(String.valueOf(t.matriz[2][1]));
                btn9.setText(String.valueOf(t.matriz[2][2]));

                if(btn1.getText().equals("-1")) btn1.setText("");
                else if(btn2.getText().equals("-1")) btn2.setText("");
                else if(btn3.getText().equals("-1")) btn3.setText("");
                else if(btn4.getText().equals("-1")) btn4.setText("");
                else if(btn5.getText().equals("-1")) btn5.setText("");
                else if(btn6.getText().equals("-1")) btn6.setText("");
                else if(btn7.getText().equals("-1")) btn7.setText("");
                else if(btn8.getText().equals("-1")) btn8.setText("");
                else if(btn9.getText().equals("-1")) btn9.setText("");

                tfNumPassos.setText(cont + "");
                cont++;
                
                int tempo = 1000;
                
                if (jogo.getListaResultado().size() > 15 && jogo.getListaResultado().size() <= 30) {
                    tempo = 700;
                }
                else if (jogo.getListaResultado().size() <= 100) {
                    tempo = 400;
                }
                else if (jogo.getListaResultado().size() <= 1000){
                    
                    tempo = 50;
                }
                else if (jogo.getListaResultado().size() <= 10000) {
                    tempo = 5;
                }
                else tempo = 1;
                
                try {
                    this.sleep(tempo);
                } catch (InterruptedException ex) {
                    Logger.getLogger(IUPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                }
            }    
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblMetodo;
    private javax.swing.JRadioButton radioAnicacaoON;
    private javax.swing.JRadioButton radioAnimacaoOFF;
    private javax.swing.JTextField tfNumPassos;
    // End of variables declaration//GEN-END:variables

    
    
}
